- name: systemd daemon-reload
  shell: systemctl daemon-reload

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart archsync
  systemd:
    name: archsync
    state: restarted

- name: reload sysctl
  shell: sysctl -p /etc/sysctl.d/*.conf

- name: restart certbot-renew.timer
  systemd:
    name: certbot-renew.timer
    state: restarted
