- name: systemd daemon-reload
  shell: systemctl daemon-reload

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart archsync
  systemd:
    name: archsync
    state: restarted
